# Generated by Django 3.0.8 on 2020-07-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gps',
            name='latitude',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='gps',
            name='longitude',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='gps',
            name='sick1',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gps',
            name='sick2',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gps',
            name='sick3',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gps',
            name='sick4',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gps',
            name='sick5',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gps',
            name='sick6',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gps',
            name='sick7',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
