# Generated by Django 3.0.8 on 2020-09-20 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0002_cut_coin_user_cut_coin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cut_coin',
            options={'verbose_name': 'แลกแต้มสะสม', 'verbose_name_plural': 'แลกแต้มสะสม'},
        ),
        migrations.AlterModelOptions(
            name='user_cut_coin',
            options={'verbose_name': 'แลกแต้มสะสมของนิสิต', 'verbose_name_plural': 'แลกแต้มสะสมของนิสิต'},
        ),
        migrations.AddField(
            model_name='cut_coin',
            name='status',
            field=models.BooleanField(default=True, verbose_name='เปิดการใช้งาน'),
        ),
        migrations.AlterField(
            model_name='cut_coin',
            name='etc',
            field=models.CharField(default='ไม่มีรายนะเอียด', max_length=150),
        ),
        migrations.AlterField(
            model_name='user_cut_coin',
            name='cut_coin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkin.cut_coin', verbose_name='แลกแต้มสะสม'),
        ),
    ]
