# Generated by Django 3.0.8 on 2020-07-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0002_auto_20200715_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='points',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='point',
            name='points2',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='point',
            name='points3',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='point',
            name='points4',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='point',
            name='points5',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='point',
            name='points6',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='point',
            name='points7',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='point',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gps',
            name='sick1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gps',
            name='sick2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gps',
            name='sick3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gps',
            name='sick4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gps',
            name='sick5',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gps',
            name='sick6',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gps',
            name='sick7',
            field=models.IntegerField(default=0),
        ),
    ]
