# Generated by Django 6.0.5 on 2026-05-08 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0008_seed_activity_rewards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('suspected', 'เฝ้าระวัง/สงสัยติดเชื้อ'), ('confirmed', 'ยืนยันติดเชื้อ'), ('recovered', 'หายแล้ว'), ('cleared', 'ไม่พบเชื้อ/ปิดเคส')], default='suspected', max_length=20, verbose_name='สถานะเคส')),
                ('symptom_started_on', models.DateField(blank=True, null=True, verbose_name='วันที่เริ่มมีอาการ')),
                ('confirmed_on', models.DateField(blank=True, null=True, verbose_name='วันที่ตรวจพบ/ยืนยัน')),
                ('trace_start_date', models.DateField(blank=True, null=True, verbose_name='เริ่มไล่ timeline')),
                ('trace_end_date', models.DateField(blank=True, null=True, verbose_name='สิ้นสุดการไล่ timeline')),
                ('notes', models.TextField(blank=True, default='', verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_covid_cases', to=settings.AUTH_USER_MODEL, verbose_name='ผู้บันทึกเคส')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covid_cases', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้')),
            ],
            options={
                'verbose_name': 'เคส COVID-19',
                'verbose_name_plural': 'เคส COVID-19',
                'ordering': ('-updated_at', '-created_at'),
            },
        ),
    ]
