# Generated by Django 3.0.8 on 2020-09-16 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('การจดทะเบียนขออนุญาตผู้ประกอบกิจการหอพัก', 'การจดทะเบียนขออนุญาตผู้ประกอบกิจการหอพัก'), ('ประเภทของหอพัก', 'ประเภทของหอพัก'), ('ลักษณะของหอพัก', 'ลักษณะของหอพัก'), ('ลักษณะการเข้าพักอาศัย', 'ลักษณะการเข้าพักอาศัย'), ('สิ่งอำนวยความสะดวกภายในหอพัก ', 'สิ่งอำนวยความสะดวกภายในหอพัก'), ('ระบบรักษาความปลอดภัย', 'ระบบรักษาความปลอดภัย'), ('ทำอาหารในหอพักได้หรือไม่', 'ทำอาหารในหอพักได้หรือไม่'), ('เลี้ยงสัตว์เลี้ยงในหอพักได้หรือไม่', 'เลี้ยงสัตว์เลี้ยงในหอพักได้หรือไม่'), ('การเผยแพร่ข้อมูลหอพัก', 'การเผยแพร่ข้อมูลหอพัก')], max_length=100, verbose_name='ประเภทตัวเลือก')),
                ('value', models.CharField(max_length=100, verbose_name='ตัวเลือก')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'จัดการประเภทตัวเลือก',
                'verbose_name_plural': 'จัดการประเภทตัวเลือก',
            },
        ),
        migrations.CreateModel(
            name='Dorm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('post', models.TextField(max_length=100)),
                ('tel', models.TextField(max_length=100)),
                ('latitude', models.TextField(blank=True, default=0, null=True)),
                ('longitude', models.TextField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amphur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkin.Amphur')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkin.District')),
                ('geo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkin.Geography')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkin.Province')),
            ],
        ),
        migrations.CreateModel(
            name='DormStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other', models.CharField(max_length=100, verbose_name='อื่นๆ')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.Choice')),
                ('dorm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.Dorm')),
            ],
        ),
        migrations.CreateModel(
            name='DormDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build', models.IntegerField(default=0)),
                ('floor', models.IntegerField(default=0)),
                ('room', models.IntegerField(default=0)),
                ('all_count', models.IntegerField(default=0)),
                ('now_count', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('fan_price_month', models.IntegerField(default=0)),
                ('fan_price_day', models.IntegerField(default=0)),
                ('air_price_month', models.IntegerField(default=0)),
                ('air_price_day', models.IntegerField(default=0)),
                ('electric_unit', models.IntegerField(default=0)),
                ('water_unit', models.IntegerField(default=0)),
                ('water_month', models.IntegerField(default=0)),
                ('water_internet', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dorm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.Dorm')),
            ],
        ),
    ]
