# Generated by Django 3.0.8 on 2020-09-15 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Makefood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pricedorm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sizedorm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Typedorm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Zonedorm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dormitory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('post', models.TextField()),
                ('tel', models.TextField()),
                ('latitude', models.TextField(blank=True, default=0, null=True)),
                ('longitude', models.TextField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amphur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkin.Amphur')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkin.District')),
                ('geo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkin.Geography')),
                ('makefood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.Makefood')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.Pet')),
                ('pricedorm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.Pricedorm')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkin.Province')),
                ('sizedorm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.Sizedorm')),
                ('typedorm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.Typedorm')),
                ('zonedorm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.Zonedorm')),
            ],
        ),
    ]
