# Generated by Django 3.0.8 on 2020-09-16 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dorm',
            name='address',
            field=models.TextField(verbose_name='ที่อยู่'),
        ),
        migrations.AlterField(
            model_name='dorm',
            name='latitude',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dorm',
            name='longitude',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dorm',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ชื่อหอพัก'),
        ),
        migrations.AlterField(
            model_name='dorm',
            name='post',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dorm',
            name='tel',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dormdetail',
            name='air_price_day',
            field=models.IntegerField(default=0, verbose_name='ห้องแอร์ รายวัน '),
        ),
        migrations.AlterField(
            model_name='dormdetail',
            name='air_price_month',
            field=models.IntegerField(default=0, verbose_name='ห้องแอร์ รายเดือน '),
        ),
        migrations.AlterField(
            model_name='dormdetail',
            name='all_count',
            field=models.IntegerField(default=0, verbose_name='บรรจุผู้อาศัย รวมทั้งหมด'),
        ),
        migrations.AlterField(
            model_name='dormdetail',
            name='build',
            field=models.IntegerField(default=0, verbose_name='จำนวนอาคาร'),
        ),
        migrations.AlterField(
            model_name='dormdetail',
            name='electric_unit',
            field=models.IntegerField(default=0, verbose_name='อัตราค่าไฟฟ้า หน่วยละ '),
        ),
        migrations.AlterField(
            model_name='dormdetail',
            name='fan_price_day',
            field=models.IntegerField(default=0, verbose_name='ห้องพัดลม รายวัน '),
        ),
        migrations.AlterField(
            model_name='dormdetail',
            name='fan_price_month',
            field=models.IntegerField(default=0, verbose_name='ห้องพัดลม รายเดือน '),
        ),
        migrations.AlterField(
            model_name='dormdetail',
            name='floor',
            field=models.IntegerField(default=0, verbose_name='จำนวนชั้น'),
        ),
        migrations.AlterField(
            model_name='dormdetail',
            name='height',
            field=models.IntegerField(default=0, verbose_name='ความยาว'),
        ),
        migrations.AlterField(
            model_name='dormdetail',
            name='now_count',
            field=models.IntegerField(default=0, verbose_name='จำนวนนิสิตที่พักอาศัย ณ ปัจจุบัน'),
        ),
        migrations.AlterField(
            model_name='dormdetail',
            name='room',
            field=models.IntegerField(default=0, verbose_name='จำนวนห้อง'),
        ),
        migrations.AlterField(
            model_name='dormdetail',
            name='water_internet',
            field=models.IntegerField(default=0, verbose_name='อัตราค่าบริการอินเตอร์เน็ตรายเดือน '),
        ),
        migrations.AlterField(
            model_name='dormdetail',
            name='water_month',
            field=models.IntegerField(default=0, verbose_name='อัตราค่าน้ำประปา คน/เดือน'),
        ),
        migrations.AlterField(
            model_name='dormdetail',
            name='water_unit',
            field=models.IntegerField(default=0, verbose_name='อัตราค่าน้ำประปา หน่วยละ '),
        ),
        migrations.AlterField(
            model_name='dormdetail',
            name='width',
            field=models.IntegerField(default=0, verbose_name='ความกว้าง'),
        ),
    ]
