# Generated by Django 3.0.8 on 2020-09-16 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0002_auto_20200916_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='DormImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='dorm/', verbose_name='รูปภาพลานจอดรถ')),
            ],
            options={
                'verbose_name': 'รูปภาพหอพัก',
                'verbose_name_plural': 'รูปภาพหอพัก',
            },
        ),
        migrations.AlterModelOptions(
            name='dorm',
            options={'verbose_name': 'ข้อมูลหอพัก', 'verbose_name_plural': 'ข้อมูลหอพัก'},
        ),
        migrations.AlterModelOptions(
            name='dormdetail',
            options={'verbose_name': 'ข้อมูลอื่นๆของหอพัก', 'verbose_name_plural': 'ข้อมูลอื่นๆของหอพัก'},
        ),
        migrations.AlterModelOptions(
            name='dormstyle',
            options={'verbose_name': 'รายละเอียดหอพัก', 'verbose_name_plural': 'รายละเอียดหอพัก'},
        ),
        migrations.AlterField(
            model_name='dormstyle',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.Choice', verbose_name='ตัวเลือก'),
        ),
        migrations.AlterField(
            model_name='dormstyle',
            name='other',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='อื่นๆ'),
        ),
    ]
