# Generated by Django 3.0.8 on 2020-09-16 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0003_auto_20200916_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='dormimage',
            name='dorm',
            field=models.ForeignKey(default='23', on_delete=django.db.models.deletion.CASCADE, to='dormitory.Dorm'),
            preserve_default=False,
        ),
    ]
