# Generated by Django 3.0.8 on 2020-09-16 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0004_dormimage_dorm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dormimage',
            old_name='image',
            new_name='car',
        ),
        migrations.AddField(
            model_name='dormimage',
            name='all_dorm',
            field=models.FileField(blank=True, null=True, upload_to='dorm/', verbose_name='รูปภาพมุมกว้างของหอพัก'),
        ),
        migrations.AddField(
            model_name='dormimage',
            name='bed',
            field=models.FileField(blank=True, null=True, upload_to='dorm/', verbose_name='รูปภาพเตียงนอน'),
        ),
        migrations.AddField(
            model_name='dormimage',
            name='closet',
            field=models.FileField(blank=True, null=True, upload_to='dorm/', verbose_name='รูปภาพตู้เสื้อผ้า'),
        ),
        migrations.AddField(
            model_name='dormimage',
            name='front',
            field=models.FileField(blank=True, null=True, upload_to='dorm/', verbose_name='รูปป้ายชื่อหน้าหอพัก'),
        ),
        migrations.AddField(
            model_name='dormimage',
            name='front_room',
            field=models.FileField(blank=True, null=True, upload_to='dorm/', verbose_name='รูปภาพหน้าห้องพัก'),
        ),
        migrations.AddField(
            model_name='dormimage',
            name='in_room',
            field=models.FileField(blank=True, null=True, upload_to='dorm/', verbose_name='รูปภาพภายในห้องพัก'),
        ),
        migrations.AddField(
            model_name='dormimage',
            name='wc',
            field=models.FileField(blank=True, null=True, upload_to='dorm/', verbose_name='รูปภาพห้องน้ำ'),
        ),
    ]
