# Generated by Django 3.0.8 on 2020-09-16 08:08

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
        ('dormitory', '0006_auto_20200916_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
                ('beta', models.BooleanField(default=True)),
                ('body', ckeditor.fields.RichTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='dormowner',
            name='dorm',
            field=models.ForeignKey(default='12', on_delete=django.db.models.deletion.CASCADE, to='dormitory.Dorm'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dorm',
            name='amphur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkin.Amphur', verbose_name='อำเภอ'),
        ),
        migrations.AlterField(
            model_name='dorm',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkin.District', verbose_name='ตำบล'),
        ),
        migrations.AlterField(
            model_name='dorm',
            name='geo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkin.Geography', verbose_name='ภูมิภาค'),
        ),
        migrations.AlterField(
            model_name='dorm',
            name='post',
            field=models.CharField(max_length=100, verbose_name='รหัสไปรศณีย์'),
        ),
        migrations.AlterField(
            model_name='dorm',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkin.Province', verbose_name='จังหวัด'),
        ),
        migrations.AlterField(
            model_name='dorm',
            name='tel',
            field=models.CharField(max_length=100, verbose_name='เบอร์โทร'),
        ),
    ]
