# Generated by Django 3.0.8 on 2020-09-16 08:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0007_auto_20200916_1508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'ตั้งค่าหน้า เกี่ยวกับ', 'verbose_name_plural': 'ตั้งค่าหน้า เกี่ยวกับ'},
        ),
        migrations.AlterField(
            model_name='about',
            name='beta',
            field=models.BooleanField(default=True, verbose_name='อยู่ในช่วงพัฒนา'),
        ),
        migrations.AlterField(
            model_name='about',
            name='body',
            field=ckeditor.fields.RichTextField(verbose_name='เนื้อหา'),
        ),
        migrations.AlterField(
            model_name='about',
            name='text',
            field=models.CharField(max_length=255, verbose_name='เนื้อหาย่อย'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(max_length=255, verbose_name='หัวข้อ'),
        ),
    ]
