# Generated by Django 3.0.8 on 2020-09-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0009_auto_20200916_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='name',
            field=models.CharField(choices=[('การจดทะเบียนขออนุญาตผู้ประกอบกิจการหอพัก', 'การจดทะเบียนขออนุญาตผู้ประกอบกิจการหอพัก'), ('โซนหอพัก', 'โซนหอพัก'), ('ประเภทของหอพัก', 'ประเภทของหอพัก'), ('ลักษณะของหอพัก', 'ลักษณะของหอพัก'), ('ลักษณะการเข้าพักอาศัย', 'ลักษณะการเข้าพักอาศัย'), ('สิ่งอำนวยความสะดวกภายในหอพัก ', 'สิ่งอำนวยความสะดวกภายในหอพัก'), ('ระบบรักษาความปลอดภัย', 'ระบบรักษาความปลอดภัย'), ('ทำอาหารในหอพักได้หรือไม่', 'ทำอาหารในหอพักได้หรือไม่'), ('เลี้ยงสัตว์เลี้ยงในหอพักได้หรือไม่', 'เลี้ยงสัตว์เลี้ยงในหอพักได้หรือไม่'), ('การเผยแพร่ข้อมูลหอพัก', 'การเผยแพร่ข้อมูลหอพัก'), ('ราคาหอพัก', 'ราคาหอพัก')], max_length=100, verbose_name='ประเภทตัวเลือก'),
        ),
        migrations.AlterField(
            model_name='dormdetail',
            name='water_month',
            field=models.CharField(default='ต่อคน', max_length=100, verbose_name='อัตราค่าน้ำประปา คน/หน่วย'),
        ),
        migrations.AlterField(
            model_name='dormdetail',
            name='water_unit',
            field=models.IntegerField(default=0, verbose_name='อัตราค่าน้ำประปา '),
        ),
        migrations.AlterField(
            model_name='dormowner',
            name='type_owner',
            field=models.CharField(blank=True, choices=[('เจ้าของหอพักดูแลเอง', 'เจ้าของหอพักดูแลเอง'), ('แม่บ้าน / คนงานดูแล', 'แม่บ้าน / คนงานดูแล')], max_length=100, null=True, verbose_name='ตำแหน่ง'),
        ),
    ]
