# Generated by Django 6.0.5 on 2026-05-07 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0011_userdorm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdorm',
            options={'verbose_name': 'นิสิตในหอพัก', 'verbose_name_plural': 'นิสิตในหอพัก'},
        ),
        migrations.AlterField(
            model_name='userdorm',
            name='dorm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.dorm', verbose_name='หอพัก'),
        ),
        migrations.AlterField(
            model_name='userdorm',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='นิสิต'),
        ),
    ]
